version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
       pip install --upgrade pip
    
    # Install dependencies needed for running the static analysis
       pip install -r requirements.txt
       pip install  pylint
  pre_build:
    commands:
       python --version
       pylint $CODEBUILD_SRC_DIR/environment/newjobportal/job/*.py
       pylint $CODEBUILD_SRC_DIR/environment/newjobportal/jobapp/*.py
     artifacts:
       files:
          - '**/*'
