# Generated by Django 3.0 on 2021-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_auto_20210428_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1', 'FT Contract'), ('2', 'PT Contract'), ('3', 'Intern Contract')], max_length=1),
        ),
    ]
